// @generated automatically by Diesel CLI.

/// A module containing custom SQL type definitions
///
/// (Automatically generated by Diesel.)
pub mod sql_types {
    /// The `access` SQL type
    ///
    /// (Automatically generated by Diesel.)
    #[derive(diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "access"))]
    pub struct Access;

    /// The `language` SQL type
    ///
    /// (Automatically generated by Diesel.)
    #[derive(diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "language"))]
    pub struct Language;

    /// The `team_fields` SQL type
    ///
    /// (Automatically generated by Diesel.)
    #[derive(diesel::sql_types::SqlType)]
    #[diesel(postgres_type(name = "team_fields"))]
    pub struct TeamFields;
}

diesel::table! {
    /// Representation of the `address` table.
    ///
    /// (Automatically generated by Diesel.)
    address (id) {
        /// The `id` column of the `address` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `address_text` column of the `address` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        address_text -> Text,
        /// The `latitude` column of the `address` table.
        ///
        /// Its SQL type is `Float8`.
        ///
        /// (Automatically generated by Diesel.)
        latitude -> Float8,
        /// The `longitude` column of the `address` table.
        ///
        /// Its SQL type is `Float8`.
        ///
        /// (Automatically generated by Diesel.)
        longitude -> Float8,
    }
}

diesel::table! {
    /// Representation of the `cook_and_run` table.
    ///
    /// (Automatically generated by Diesel.)
    cook_and_run (id) {
        /// The `id` column of the `cook_and_run` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `cook_and_run` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Text,
        /// The `name` column of the `cook_and_run` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `created` column of the `cook_and_run` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created -> Timestamptz,
        /// The `edited` column of the `cook_and_run` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        edited -> Timestamptz,
        /// The `occur` column of the `cook_and_run` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        occur -> Timestamptz,
        /// The `start_point` column of the `cook_and_run` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        start_point -> Nullable<Uuid>,
        /// The `end_point` column of the `cook_and_run` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        end_point -> Nullable<Uuid>,
        /// The `share_team_config` column of the `cook_and_run` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        share_team_config -> Nullable<Uuid>,
        /// The `plan` column of the `cook_and_run` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        plan -> Nullable<Uuid>,
        /// The `plan_config` column of the `cook_and_run` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        plan_config -> Nullable<Uuid>,
    }
}

diesel::table! {
    /// Representation of the `course` table.
    ///
    /// (Automatically generated by Diesel.)
    course (id) {
        /// The `id` column of the `course` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `cook_and_run_id` column of the `course` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        cook_and_run_id -> Uuid,
        /// The `name` column of the `course` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `time` column of the `course` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        time -> Text,
        /// The `has_multiple_hosts` column of the `course` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        has_multiple_hosts -> Bool,
    }
}

diesel::table! {
    /// Representation of the `hosting` table.
    ///
    /// (Automatically generated by Diesel.)
    hosting (id) {
        /// The `id` column of the `hosting` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `plan_id` column of the `hosting` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        plan_id -> Uuid,
        /// The `course_id` column of the `hosting` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        course_id -> Uuid,
        /// The `team_id` column of the `hosting` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        team_id -> Uuid,
        /// The `guest_team_ids` column of the `hosting` table.
        ///
        /// Its SQL type is `Jsonb`.
        ///
        /// (Automatically generated by Diesel.)
        guest_team_ids -> Jsonb,
    }
}

diesel::table! {
    /// Representation of the `note` table.
    ///
    /// (Automatically generated by Diesel.)
    note (id) {
        /// The `id` column of the `note` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `team_id` column of the `note` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        team_id -> Uuid,
        /// The `headline` column of the `note` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        headline -> Text,
        /// The `content` column of the `note` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        content -> Text,
        /// The `created` column of the `note` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created -> Timestamptz,
    }
}

diesel::table! {
    /// Representation of the `plan` table.
    ///
    /// (Automatically generated by Diesel.)
    plan (id) {
        /// The `id` column of the `plan` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `data` column of the `plan` table.
        ///
        /// Its SQL type is `Jsonb`.
        ///
        /// (Automatically generated by Diesel.)
        data -> Jsonb,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use super::sql_types::Access;
    use super::sql_types::Language;

    /// Representation of the `plan_config` table.
    ///
    /// (Automatically generated by Diesel.)
    plan_config (id) {
        /// The `id` column of the `plan_config` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `access` column of the `plan_config` table.
        ///
        /// Its SQL type is `Array<Nullable<Access>>`.
        ///
        /// (Automatically generated by Diesel.)
        access -> Array<Nullable<Access>>,
        /// The `titel` column of the `plan_config` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        title -> Text,
        /// The `description` column of the `plan_config` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Text,
        /// The `date` column of the `plan_config` table.
        ///
        /// Its SQL type is `Date`.
        ///
        /// (Automatically generated by Diesel.)
        date -> Date,
        /// The `language` column of the `plan_config` table.
        ///
        /// Its SQL type is `Language`.
        ///
        /// (Automatically generated by Diesel.)
        language -> Language,
    }
}

diesel::table! {
    /// Representation of the `point` table.
    ///
    /// (Automatically generated by Diesel.)
    point (id) {
        /// The `id` column of the `point` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `address` column of the `point` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        address -> Uuid,
        /// The `name` column of the `point` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `time` column of the `point` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        time -> Text,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use super::sql_types::TeamFields;

    /// Representation of the `share` table.
    ///
    /// (Automatically generated by Diesel.)
    share (id) {
        /// The `id` column of the `share` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `created` column of the `share` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created -> Timestamptz,
        /// The `invite_text` column of the `share` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        invite_text -> Text,
        /// The `needs_login` column of the `share` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        needs_login -> Bool,
        /// The `default_needs_check` column of the `share` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        default_needs_check -> Bool,
        /// The `required_fields` column of the `share` table.
        ///
        /// Its SQL type is `Nullable<Array<Nullable<TeamFields>>>`.
        ///
        /// (Automatically generated by Diesel.)
        required_fields -> Nullable<Array<Nullable<TeamFields>>>,
        /// The `max_teams` column of the `share` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        max_teams -> Nullable<Int4>,
        /// The `registration_deadline` column of the `share` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        registration_deadline -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// Representation of the `team` table.
    ///
    /// (Automatically generated by Diesel.)
    team (id) {
        /// The `id` column of the `team` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `cook_and_run_id` column of the `team` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        cook_and_run_id -> Uuid,
        /// The `created_by_user` column of the `team` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        created_by_user -> Nullable<Text>,
        /// The `name` column of the `team` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `created` column of the `team` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created -> Timestamptz,
        /// The `edited` column of the `team` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        edited -> Timestamptz,
        /// The `address` column of the `team` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        address -> Uuid,
        /// The `mail` column of the `team` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        mail -> Nullable<Text>,
        /// The `phone` column of the `team` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        phone -> Nullable<Text>,
        /// The `members` column of the `team` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        members -> Nullable<Int4>,
        /// The `diets` column of the `team` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        diets -> Nullable<Text>,
        /// The `needs_check` column of the `team` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        needs_check -> Bool,
    }
}

diesel::joinable!(cook_and_run -> plan (plan));
diesel::joinable!(cook_and_run -> plan_config (plan_config));
diesel::joinable!(cook_and_run -> share (share_team_config));
diesel::joinable!(course -> cook_and_run (cook_and_run_id));
diesel::joinable!(hosting -> course (course_id));
diesel::joinable!(hosting -> plan (plan_id));
diesel::joinable!(hosting -> team (team_id));
diesel::joinable!(note -> team (team_id));
diesel::joinable!(point -> address (address));
diesel::joinable!(team -> address (address));
diesel::joinable!(team -> cook_and_run (cook_and_run_id));

diesel::allow_tables_to_appear_in_same_query!(
    address,
    cook_and_run,
    course,
    hosting,
    note,
    plan,
    plan_config,
    point,
    share,
    team,
);
